# Generated by Django 4.0.2 on 2022-03-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mfcc_parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_length', models.FloatField()),
                ('overlap', models.FloatField()),
                ('mfcc_coefficient', models.IntegerField()),
            ],
        ),
    ]
