# Generated by Django 4.0.2 on 2022-03-04 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfcc_parameters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mfcc_parameters',
            table='mfcc_parameters',
        ),
    ]
